openapi: 3.0.3
info:
  title: Promotions & Coupons API
  description: API endpoints for managing promotional coupons and applying discounts to orders
  version: 1.0.0

paths:
  /api/v1/orders/{orderId}/coupon:
    post:
      summary: Apply coupon to order
      description: Applies a coupon code to a draft order, calculating and applying the discount
      operationId: applyCoupon
      tags:
        - Order Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
          description: Order ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyCouponRequest'
      responses:
        '200':
          description: Coupon applied successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderWithCouponResponse'
        '403':
          description: Forbidden - user does not have access to this order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error - invalid or ineligible coupon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many invalid coupon attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Remove coupon from order
      description: Removes the applied coupon from a draft order (idempotent)
      operationId: removeCoupon
      tags:
        - Order Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
          description: Order ID
      responses:
        '200':
          description: Coupon removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderWithCouponResponse'
        '403':
          description: Forbidden - user does not have access to this order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/coupons:
    get:
      summary: List coupons
      description: Returns a paginated list of coupons with optional filters
      operationId: listCoupons
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
        - name: code
          in: query
          schema:
            type: string
          description: Filter by coupon code (partial match)
        - name: starts_after
          in: query
          schema:
            type: string
            format: date-time
          description: Filter coupons starting after this date
        - name: ends_before
          in: query
          schema:
            type: string
            format: date-time
          description: Filter coupons ending before this date
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: per_page
          in: query
          schema:
            type: integer
            default: 15
            maximum: 100
          description: Items per page
      responses:
        '200':
          description: List of coupons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponListResponse'

    post:
      summary: Create coupon
      description: Creates a new coupon
      operationId: createCoupon
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCouponRequest'
      responses:
        '201':
          description: Coupon created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/coupons/{couponId}:
    get:
      summary: Get coupon details
      description: Returns details of a specific coupon
      operationId: getCoupon
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
      responses:
        '200':
          description: Coupon details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponResponse'
        '404':
          description: Coupon not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Update coupon
      description: Updates an existing coupon
      operationId: updateCoupon
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCouponRequest'
      responses:
        '200':
          description: Coupon updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponResponse'
        '404':
          description: Coupon not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete coupon
      description: Soft deletes a coupon
      operationId: deleteCoupon
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
      responses:
        '204':
          description: Coupon deleted successfully
        '404':
          description: Coupon not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/coupons/{couponId}/targets:
    get:
      summary: List coupon targets
      description: Returns all targets (categories/menu items) attached to a coupon
      operationId: listCouponTargets
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
      responses:
        '200':
          description: List of targets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponTargetListResponse'

    post:
      summary: Add target to coupon
      description: Attaches a category or menu item target to a coupon
      operationId: addCouponTarget
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCouponTargetRequest'
      responses:
        '201':
          description: Target added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponTargetResponse'
        '409':
          description: Target already attached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/coupons/{couponId}/targets/{targetId}:
    delete:
      summary: Remove target from coupon
      description: Removes a target from a coupon
      operationId: removeCouponTarget
      tags:
        - Admin Coupons
      security:
        - bearerAuth: []
      parameters:
        - name: couponId
          in: path
          required: true
          schema:
            type: integer
          description: Coupon ID
        - name: targetId
          in: path
          required: true
          schema:
            type: integer
          description: Target ID
      responses:
        '204':
          description: Target removed successfully
        '404':
          description: Target not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ApplyCouponRequest:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          maxLength: 50
          example: WELCOME10

    CreateCouponRequest:
      type: object
      required:
        - code
        - discount_type
        - discount_value
      properties:
        code:
          type: string
          maxLength: 50
          example: SUMMER20
        name:
          type: string
          maxLength: 255
          nullable: true
          example: Summer Sale 20%
        discount_type:
          type: string
          enum: [percent, fixed]
          example: percent
        discount_value:
          type: number
          format: decimal
          minimum: 0
          example: 20.00
        currency:
          type: string
          minLength: 3
          maxLength: 3
          nullable: true
          description: Required for fixed discount type
          example: PLN
        starts_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-06-01T00:00:00Z"
        ends_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-08-31T23:59:59Z"
        min_subtotal:
          type: integer
          minimum: 0
          description: Minimum order subtotal in minor units (cents)
          example: 5000
        max_uses_total:
          type: integer
          minimum: 1
          nullable: true
          example: 1000
        max_uses_per_customer:
          type: integer
          minimum: 1
          nullable: true
          example: 1
        is_active:
          type: boolean
          default: true

    UpdateCouponRequest:
      type: object
      properties:
        code:
          type: string
          maxLength: 50
        name:
          type: string
          maxLength: 255
          nullable: true
        discount_type:
          type: string
          enum: [percent, fixed]
        discount_value:
          type: number
          format: decimal
          minimum: 0
        currency:
          type: string
          minLength: 3
          maxLength: 3
          nullable: true
        starts_at:
          type: string
          format: date-time
          nullable: true
        ends_at:
          type: string
          format: date-time
          nullable: true
        min_subtotal:
          type: integer
          minimum: 0
        max_uses_total:
          type: integer
          minimum: 1
          nullable: true
        max_uses_per_customer:
          type: integer
          minimum: 1
          nullable: true
        is_active:
          type: boolean

    CreateCouponTargetRequest:
      type: object
      required:
        - target_type
        - target_id
      properties:
        target_type:
          type: string
          enum: [category, menu_item]
          example: category
        target_id:
          type: integer
          minimum: 1
          example: 5

    Coupon:
      type: object
      properties:
        id:
          type: integer
          example: 1
        code:
          type: string
          example: SUMMER20
        name:
          type: string
          nullable: true
          example: Summer Sale 20%
        discount_type:
          type: string
          enum: [percent, fixed]
          example: percent
        discount_value:
          type: string
          example: "20.00"
        currency:
          type: string
          nullable: true
          example: null
        starts_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-06-01T00:00:00+00:00"
        ends_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-08-31T23:59:59+00:00"
        min_subtotal:
          type: integer
          example: 5000
        max_uses_total:
          type: integer
          nullable: true
          example: 1000
        max_uses_per_customer:
          type: integer
          nullable: true
          example: 1
        is_active:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
          example: "2026-02-02T10:00:00+00:00"
        updated_at:
          type: string
          format: date-time
          example: "2026-02-02T10:00:00+00:00"

    CouponTarget:
      type: object
      properties:
        id:
          type: integer
          example: 1
        coupon_id:
          type: integer
          example: 1
        target_type:
          type: string
          enum: [category, menu_item]
          example: category
        target_id:
          type: integer
          example: 5
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    OrderWithCoupon:
      type: object
      properties:
        id:
          type: integer
          example: 123
        status:
          type: string
          example: draft
        subtotal:
          type: integer
          description: Subtotal in minor units (cents)
          example: 5000
        discount_total:
          type: integer
          description: Discount amount in minor units (cents)
          example: 500
        total:
          type: integer
          description: Total after discount in minor units (cents)
          example: 4500
        currency:
          type: string
          example: PLN
        coupon:
          type: object
          nullable: true
          properties:
            code:
              type: string
              example: WELCOME10
            discount_type:
              type: string
              enum: [percent, fixed]
              example: percent
            discount_value:
              type: string
              example: "10.00"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CouponResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Coupon'
        meta:
          type: object

    CouponListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Coupon'
        meta:
          type: object
          properties:
            current_page:
              type: integer
              example: 1
            per_page:
              type: integer
              example: 15
            total:
              type: integer
              example: 50
            last_page:
              type: integer
              example: 4

    CouponTargetResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CouponTarget'
        meta:
          type: object

    CouponTargetListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CouponTarget'
        meta:
          type: object

    OrderWithCouponResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderWithCoupon'
        meta:
          type: object

    Error:
      type: object
      properties:
        title:
          type: string
          example: Validation Error
        detail:
          type: string
          example: This coupon code is not valid
        status:
          type: integer
          example: 422
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        trace_id:
          type: string
          example: abc123-def456
